version: '3.8'

services:
  agricultural-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agricultural-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped

# No nginx, no complex networking - just your app
